# GenericAudioOutputMethod "direct"

# GenericExecuteSynth "/home/t/n/scripts/piper-wrapper2.sh \"$DATA\" $LANGUAGE $VOICE $PITCH $PITCH_RANGE $RATE"
GenericExecuteSynth "printf %s \'$DATA\' | /home/t/n/scripts/piper-wrappers.sh $LANGUAGE $VOICE $PITCH $PITCH_RANGE $RATE"

GenericLanguage "en" "en-US" "utf-8"
GenericLanguage "en-US" "en-US" "utf-8"
GenericLanguage "en-us" "en-US" "utf-8"
GenericLanguage "en-gb" "en-GB" "utf-8"

# AddVoice "en-GB" "female1" "en_GB-alba-medium"
# AddVoice "en-GB" "male1" "en_GB-northern_english_male-medium"
# AddVoice "en-GB" "female2" "en_GB-southern_english_female-low"
# AddVoice "en-US" "female1" "en_US-amy-medium"
# AddVoice "en-US" "female2" "en_US-hfc_female-medium"
# AddVoice "en-US" "male1" "en_US-joe-medium"
# AddVoice "en-US" "female3" "en_US-kathleen-low"
# AddVoice "en-US" "male2" "en_US-norman-medium"
# AddVoice "es" "male1" "es_ES-davefx-medium"
# AddVoice "es" "female1" "es_MX-claude-high"


AddVoice "en-GB" "male1" "en_GB-alan-medium"
AddVoice "en-US" "female1" "en_US-libritts_r-medium"
AddVoice "en-US" "female2" "en_US-libritts-high"
DefaultVoice "en_US-libritts_r-medium"
# DefaultVoice "en_US-libritts-high"
