alias p="paru"
alias pqi="paru -Qi"
alias pql="paru -Ql"
alias pqe="paru -Qe"
alias pqk="paru -Qk"
alias pqs="paru -Qs"
alias psi="paru -Si"
alias pss="paru -Ss"
alias psy="paru -Sy"
alias psyu="paru -Syu"
alias psu="paru -Su"
alias psuu="paru -Suu"
# alias pi="paru -S"
alias pU "paru -U"
alias pideps="paru -S --asdeps"
alias pr="paru -Rsu"
alias pc="paru -Rsuc"
alias po="paru -Rs (pacman -Qqtd)"
alias prepo="paru --repo"
alias paur="paru --aur"

alias y="yay"
alias yr="yay --repo"
alias yaur="yay --aur"
alias yi="yay -S"

alias hx="helix"
set -Ux EDITOR helix
# set -Ux http_proxy socks://127.0.0.1:7890
# set -Ux https_proxy socks://127.0.0.1:7890
