alias p="sudo pacman"
alias pqi="sudo pacman -Qi"
alias pql="sudo pacman -Ql"
alias pqe="sudo pacman -Qe"
alias pqk="sudo pacman -Qk"
alias pqs="sudo pacman -Qs"
alias psi="sudo pacman -Si"
alias pss="sudo pacman -Ss"
alias psy="sudo pacman -Sy"
alias psyu="sudo pacman -Syu"
alias psu="sudo pacman -Su"
alias psuu="sudo pacman -Suu"
alias pi="sudo pacman -S"
alias pU "sudo pacman -U"
alias pideps="sudo pacman -S --asdeps"
alias pr="sudo pacman -Rsu"
alias pc="sudo pacman -Rsuc"
alias po="sudo pacman -Rs (pacman -Qqtd)"
alias y="yay"
alias yr="yay --repo"
alias yaur="yay --aur"
alias yi="yay -S"

alias hx="helix"
set -Ux EDITOR helix
# set -Ux http_proxy socks://127.0.0.1:7890
# set -Ux https_proxy socks://127.0.0.1:7890
