watch-later-directory = ~/.cache/mpv/watch_later
sub-file-paths=sub:subs:Sub:Subs:.
# sub-file-paths = sub;subs;Sub;Subs;.
# hwdec = auto
# hwdec = auto
# hwdec = vaapi-copy
# hwdec = auto-copy
hwdec = vulkan-copy
# hwdec = no
# hwdec = vulkan
pipewire-buffer = 2000

display-fps-override=60

profile=high-quality
# vo = xv
# vo = gpu-next
# gpu-api = opengl
# gpu-api = vulkan
# gpu-api = d3d11
# gpu-context=d3d11


# glsl-shader="~~/shaders/hdeband.glsl"

# glsl-shader="~~/shaders/artcnn/ArtCNN_C4F16.glsl"
# glsl-shader="~~/shaders/artcnn/ArtCNN_C4F32.glsl"
# glsl-shader="~~/shaders/ravu-zoom-ar-r3.hook"
glsl-shader="~~/shaders/ravu-lite-ar-r4.hook"

# glsl-shader="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
# glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
# glsl-shader="~~/shaders/AMD/FSR.glsl"
# glsl-shader="~~/shaders/AMD/CAS.glsl"

# glsl-shader="~~/shaders/SSimSuperRes.glsl"
# glsl-shader="~~/shaders/adaptive-sharpen.glsl"

glsl-shader="~~/shaders/CfL_Prediction.glsl"
glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/SSimDownscaler.glsl"

# video-sync=display-resample
# video-sync=display-resample-vdrop
# video-sync=display-vdrop
interpolation=yes
tscale=hermite

scale=ewa_lanczossharp
cscale=ewa_lanczos
dscale=hermite
correct-downscaling=yes
linear-downscaling=no
sigmoid-upscaling=yes
include=~~/hdr-toys.conf


deinterlace=auto
deband=yes
deband-iterations=2
deband-threshold=34
deband-range=16
deband-grain=48

dither-depth=auto
# dither=error-diffusion
# vd-lavc-o=deint=bob

sub-use-margins = yes
sub-auto = all
demuxer-mkv-subtitle-preroll = yes
sub-fix-timing = yes
slang = English(SDH),English (SDH),eng,en,english,enUS,en?,eng?,*_English,en,eng,english,English,enUS,en-US
# slang = 'English(SDH),English (SDH),eng,en,english,enUS,en?,eng?,*_English,en,eng,english,English,enUS,en-US'

alang=ja,jp,jpn,japanese,en,eng,english,English,enUS,en-US
# slang=ja,jp,jpn,japanese,en,eng,english,English,enUS,en-US
# slang=eng,en

sub-gray
sub-border-size = 1
# sub-border-size = 0
# sub-border-size = 2
# sub-brightness=30
# sub-contrast=30
# sub-gamma=0
sub-font-size = 28
sub-font = 'sans-serif'

osd-font-size = 32
# osd-font = 'sans-serif'
# osd-font = 'UbuntuMono Nerd Font'
# osd-font = 'Ubuntu Sans Mono'
osd-font = 'Cascadia Code'
# osd-font = 'monospace'
osd-on-seek = msg
osc=no
osd-bar=no
msg-color = yes # color log messages on terminal
term-osd-bar = yes # displays a progress bar on the terminal

ontop = yes
border=no
keep-open=yes
# autofit=50%
autofit-larger=75%
cursor-autohide=100

save-position-on-quit
volume-max = 100
force-seekable = yes
cache = yes
demuxer-readahead-secs=600
demuxer-max-bytes=50M
demuxer-max-back-bytes=200M
# ytdl=yes
# ytdl_path=yt-dlp
# ytdl-raw-options=format-sort=res:2160,vcodec,hdr:sdr
# ytdl-raw-options=format-sort=res:2160,vcodec,hdr:sdr
# ytdl-raw-options=embed-chapters=
# ytdl-raw-options=sub-lang="en,ja,en.*",write-sub=,write-auto-sub=

input-media-keys= no
